### ISSUE TITLE
Missing png_read_image?

### ISSUE THREAD

**Issue by raziel-** [salass00/png16_lib#1]
I get this error when linking scummvm-tools with libpng16 (it doesn´t show up with the 2019 1.6.37 based libpng from os4depot.net)

Development:Coding/SDK/gcc/ppc-amigaos/bin/ld: Dwarf Error: found dwarf version '5', this reader only handles version 2, 3 and 4 information.
encode_dxa.o: In function `EncodeDXA::read_png_file(char const*, unsigned char*&, unsigned char*&, int&, int&)':
encode_dxa.cpp:(.text+0x3464): undefined reference to `png_read_image'
gmake: *** [scummvm-tools-cli] Error 1

gitub.com/scummvm-scummvm-tools

**Comment by salass00** [comment]
The png_read_image() function is now added to the library interface in version 53.3.

I must have just accidentally skipped over it when writing the original interfaces/png16.h header file, as it is not a new libpng function added after 1.6.34.

**Comment by raziel-** [comment]
@salass00

Thank you very much, links fine again
